### ISSUE TITLE
1.1 changes are not in the in the github repo

### ISSUE THREAD

**Issue by JanSharp** [sproott/PersonalLogisticsImportExport#1]
I wanted to make changes and fixes for the mod but i noticed that 1.1 changes are not in github yet. If you could push those that would be great, otherwise me making the same changes in a different commit would most likely cause merge conficts once i make a pull request, you merge it and then try to pull that locally where you would then be ahead *and* behind of the remote master.

**Comment by sproott** [comment]
Well, that was weird. Merge conflicts all over the place. It's pushed now.

**Comment by JanSharp** [comment]
thank you!
